#!/usr/bin/env python3
"""Refresh the model catalog in index.json from OpenRouter's public API.

- No API key required. Stdlib only. Open source (MIT).
- Picks the NEWEST text-output model matching each tier's alias_patterns.
- Atomic writes: index.json is never left half-written.
- Offline-safe: on any failure, index.json is left untouched.
- The local_zero_token tier is never auto-updated (local stays local).

Usage:
  python3 scripts/update_models.py             # update index.json
  python3 scripts/update_models.py --dry-run   # print result, write nothing
  python3 scripts/update_models.py --validate  # offline structural check (CI)
"""
import json
import os
import re
import sys
import tempfile
import urllib.request
from datetime import date
from pathlib import Path

INDEX = Path(__file__).resolve().parent.parent / "index.json"
OPENROUTER = "https://openrouter.ai/api/v1/models"
REQUIRED = ("settings", "aliases", "alias_patterns", "tasks")


def fetch(url):
    req = urllib.request.Request(url, headers={"User-Agent": "meta-skill/1.0"})
    with urllib.request.urlopen(req, timeout=25) as r:
        return json.load(r)


def cost_per_1k(m):
    p = m.get("pricing") or {}
    try:
        return round((float(p.get("prompt") or 0) + float(p.get("completion") or 0)) * 1000, 6)
    except (TypeError, ValueError):
        return 0.0


def outputs_text(m):
    """True if the model outputs text. Permissive on unknown schemas."""
    mod = ((m.get("architecture") or {}).get("modality") or "text->text")
    return "text" in str(mod).split("->")[-1]


def validate(idx):
    """Offline structural check. Returns a list of problems (empty = OK)."""
    errs = []
    for k in REQUIRED:
        if k not in idx:
            errs.append(f"missing key: {k}")
    aliases = idx.get("aliases", {})
    for tier, pats in idx.get("alias_patterns", {}).items():
        if tier not in aliases:
            errs.append(f"alias_patterns tier not in aliases: {tier}")
        for p in pats:
            try:
                re.compile(p, re.I)
            except re.error as e:
                errs.append(f"bad regex {tier}:{p!r} ({e})")
    seen = set()
    for t in idx.get("tasks", []):
        tid = t.get("id", "?")
        if tid in seen:
            errs.append(f"duplicate task id: {tid}")
        seen.add(tid)
        if not t.get("keywords"):
            errs.append(f"task {tid}: no keywords")
        for tr in [t.get("tier")] + list(t.get("fallback", [])):
            if tr not in aliases:
                errs.append(f"task {tid}: unknown tier {tr}")
    return errs


def atomic_write(path, text):
    fd, tmp = tempfile.mkstemp(dir=str(path.parent), prefix=".index-", suffix=".tmp")
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as f:
            f.write(text)
        os.replace(tmp, path)  # atomic on POSIX and Windows
    except BaseException:
        try:
            os.unlink(tmp)
        except OSError:
            pass
        raise


def main():
    try:
        idx = json.loads(INDEX.read_text(encoding="utf-8"))
    except (OSError, ValueError) as e:
        print(f"[meta-skill] cannot read index.json ({e})")
        return 1

    if "--validate" in sys.argv:
        errs = validate(idx)
        for e in errs:
            print(f"[meta-skill] INVALID: {e}")
        print(f"[meta-skill] validate: {'FAIL' if errs else 'OK'} "
              f"({len(idx.get('tasks', []))} tasks, {len(idx.get('aliases', {}))} tiers)")
        return 1 if errs else 0

    dry = "--dry-run" in sys.argv
    try:
        data = fetch(OPENROUTER)["data"]
        if not isinstance(data, list):
            raise ValueError("unexpected OpenRouter schema: 'data' is not a list")
    except Exception as e:  # offline-safe: keep last known catalog
        print(f"[meta-skill] network unavailable ({e}); index.json kept as-is")
        return 1

    models = {"note": "auto-generated by scripts/update_models.py (source: OpenRouter public API)"}
    for tier, pats in idx.get("alias_patterns", {}).items():
        rx = [re.compile(p, re.I) for p in pats]
        cand = [m for m in data
                if isinstance(m, dict) and outputs_text(m)
                and any(r.search(m.get("id") or "") for r in rx)]
        cand.sort(key=lambda m: m.get("created") or 0, reverse=True)
        if not cand:
            print(f"[meta-skill] WARNING: no models matched tier '{tier}'; keeping previous alias")
            continue
        idx["aliases"][tier] = cand[0]["id"]
        models[tier] = [
            {"id": m["id"], "cost_per_1k_usd": cost_per_1k(m), "context": m.get("context_length")}
            for m in cand[:3]
        ]
    idx["models"] = models
    idx["updated"] = date.today().isoformat()

    errs = validate(idx)
    if errs:
        print("[meta-skill] refusing to write an invalid index:")
        for e in errs:
            print(f"  {e}")
        return 1

    out = json.dumps(idx, indent=2, ensure_ascii=False) + "\n"
    if dry:
        print(out)
    else:
        atomic_write(INDEX, out)
        print(f"[meta-skill] index.json updated {idx['updated']}:")
        for t, v in idx["aliases"].items():
            print(f"  {t} -> {v}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
